### ISSUE TITLE
Desktop environment's webview failed to load

### ISSUE THREAD

**Issue by Brouilles** [ClementNerma/NightOS#1]
OS : Windows 10 Creators Update
Node.js : v8.4.0
npm : 5.4.0

Error : 
Desktop environment's webview failed to load (-6: ERR_FILE_NOT_FOUND)

Error: <unknown> at error (/sys/frame.html:132:31) at HTMLElement.webview.addEventListener.e (eval at (eval at boot (eval at ipc.on (/sys/frame.html:224:14))), :66:3) at WebViewImpl.dispatchEvent (C:\Users\dezei\Desktop\NightOS\NightOS\node_modules\electron\dist\resources\electron.asar\renderer\web-view\web-view.js:175:22) at dispatchEvent (C:\Users\dezei\Desktop\NightOS\NightOS\node_modules\electron\dist\resources\electron.asar\renderer\web-view\guest-view-internal.js:55:11) at EventEmitter. (C:\Users\dezei\Desktop\NightOS\NightOS\node_modules\electron\dist\resources\electron.asar\renderer\web-view\guest-view-internal.js:72:7) at emitMany (events.js:127:13) at EventEmitter.emit (events.js:204:7)

**Comment by Brouilles** [comment]
Hi, 
I understand the problem. After analyse your code, I see the desktop environment, so process.html doesn't exist in this project. When I created it, no problem.

I think this is normal, this repository, it's just the beginning of the project.
I will follow your project. And if there are indications and if I have the time, I would participate.
Cordially

**Comment by ClementNerma** [comment]
Thanks for your help :)
This is normal because I didn't commit the 'process.html' file for now, even if it's ready - I wait just the time to implement process support.

I think I'll start to try first to replace the error log by a pastebin link or something ^^

The problem should be solved this weekend (if I have time to make the changes).

**Comment by Brouilles** [comment]
Et je parle français si besoin, je viens de voir votre poste sur openClassRoom !
Le projet m'intéresse pas mal. Je ne suis pas expert en Node.js, mais s'il y a des choses à faire pas de problème. En tout cas projet ambitieux ! Donc je vous souhaite bonne chance pour celui-ci.

Cordialement.

**Comment by ClementNerma** [comment]
I prefer to talk in english because, even if I'm only a student and this project won't be seen by many people (because it's only a theorical operating system, afterall) I want to practice as if I had to make this project for, I don't know, an enterprise for example.

But thanks for you help :)

**Comment by Brouilles** [comment]
I understand, no problem. 
So I wait for the next push, the project interests me a lot, especially to make a fork for TV with a Raspberry Pi for example. What is the current status of the project after the next push ?

It might be interesting to have a roadmap (or I may not have seen it)
Thank you for the answer.

**Comment by ClementNerma** [comment]
The next push should add the support for processes frames (NightOS runs applications inside `<webview>` elements, for more security). But currently I'm experiencing a problem with this that makes me unable to continue until I found a solution.
The only one I currently have is very bad and would make applications running really slow. But I'll try to find a fix for that.

Also, why do you want to use this project with a Raspberry Pi ? NightOS is an HTML5 operating system, so it won't be able (at least in a first time, but I think it'll never be possible) to run executable programs at all. You'll only be able to run applications made specifically for this system, which requires to change the library you use in your original application on Windows, Linux or MacOS - or to start a scratch new application.

Even if I think NightOS could run smoothly on a Pi, I don't think this is really useful when you think to the really restricted amount of applications on it. If I have enough time (and courage) I'll developp all the native applications I want to be built in NightOS (there's 24 of them, from a simple file explorer to a full SDK, more the system applications to manage the network, hard drive etc.). But that won't be anytime soon, that's sure (at least one or two years will be required, I think, and I don't know if I'll have drop the project when this time will come).

**Comment by Brouilles** [comment]
"NightOS is an HTML5 operating system, so it won't be able (at least in a first time, but I think it'll never be possible) to run executable programs at all." - It's possible and i want this. And for a fullscreen operating system (for TV, no Window system and drag and drop). A simple switch to application in Fullscreen is sufficient. Many projects exist and make this. 

But why NightOS ? Because the project is ambitious, this one being young I can easily participate. Moreover I like the concept and with asm.js, there is way to have a code performing. Yes, I could do the same with QT for example. But that does not interest me, there is no challenge.

"I'll developp all the native " - This is an open source project, so you are not necessarily alone. ;)
I'm really interested by the project. So if I could get involved I would. I look forward to the new push !

**Comment by ClementNerma** [comment]
> And for a fullscreen operating system (for TV, no Window system and drag and drop).

NightOS will use a desktop environment, so it'll work with windows by default. But, if you really want a no-window mode, it's still simple to programmate it since the DE can be customized very simply by scripts (I could perhaps even include a mode to work without window, I think).

> this one being young I can easily participate
> This is an open source project, so you are not necessarily alone. ;)

Thanks for you help ;). But I never worked in team, and I don't really know how to... And even if I knew, this O.S.' design is very different when compared to the actual ones (Windows, Linux or Mac OS for example) : only the kernel's design and the Linux' base design are similar, but that's not the part I'll developp.

What I make is a fully-functionnal user interface with low-level management (applications management, network rules, users and permissions system...), so I'm the only one that can really understand how to implement that, at least for now.

> So if I could get involved I would.

Thanks again, I will tell you if I need help at a moment :) !

**Comment by Brouilles** [comment]
Hi ! 
News about the new push ? Because I wait for this version to suggest ways to improve or add technology. I could do my own project from scratch on my Github, but it would be useless to duplicate a similar project.

Thx 👍

**Comment by ClementNerma** [comment]
About [your last comment](https://github.com/ClementNerma/NightOS/issues/2#issuecomment-328928776), I'm currently writing down the project's documentation so you and everythone else will be able to understand how NightOS works still before it is fully developped.
