### ISSUE TITLE
Updater is broken

### ISSUE THREAD

**Issue by motezazer** [ClementNerma/NightOS#13]
Due to the new permission evaluation, updater is broken

**Comment by ClementNerma** [comment]
I dont understand.

**Comment by motezazer** [comment]
You cannot launch Updater anymore with the new update.
When you launch an upk file, it crashes.
The reason is the new rights evaluation in the package.prm : 4 isn't recognized anymore.

**Comment by ClementNerma** [comment]
Please re-test it with the last update of NightOS

**Comment by motezazer** [comment]
It still doesn't work

**Comment by motezazer** [comment]
Okay, got it.
You must change rights from Updater to "herit<4"

**Comment by motezazer** [comment]
Nope, it wasn't that.
Core.js attempt to get the first 6 characters of the string.
A number (4) is not a string.

**Comment by motezazer** [comment]
Found a REAL solution.
Every system app (that need system rights) should have "system" in rights.
"system" is a string that have 6 characters, so the condition will not fail.
Then you must add a condition after the faulty condition that replace system by 4

**Comment by ClementNerma** [comment]
I corrected that. An update will be released in few hours.
