### ISSUE TITLE
IMPORTANT : node-webkit folder

### ISSUE THREAD

**Issue by motezazer** [ClementNerma/NightOS#15]
Node-Webkit folder only require a privilege level of 3, this mean that : 
-the user can replace node-webkit without system rights
-the user can, in package.json, set the attribute toolbar to true without system rights

**Comment by ClementNerma** [comment]
Please express yourself differently because of other users can understand you (privileges level, etc.).
So, the user admin of thé machine can do many things, but not including change node-webkit files. Si i will correct that.

**Comment by ClementNerma** [comment]
I've corrected that. An update will be released in few hours.
