### ISSUE TITLE
Corrupted shortcuts

### ISSUE THREAD

**Issue by motezazer** [ClementNerma/NightOS#3]
There are two shortcuts (Recycle and Task Manager) that leads to nowhere.

**Comment by motezazer** [comment]
UPDATE : Task Manager has only a corrupted icon.

**Comment by ClementNerma** [comment]
That is caused by GitHub who doesn't want to keep empty folders (such as the recycle folder).
This will be corrected today.

**Comment by motezazer** [comment]
It's not fixed.

**Comment by ClementNerma** [comment]
I've fixed that (i've put empty files in the user directory)
