### ISSUE TITLE
Problème au bootage

### ISSUE THREAD

**Issue by ducksper** [ClementNerma/NightOS#4]
Une image sera plus parlante que moi sans doute:
![screenshot_1](https://user-images.githubusercontent.com/25124567/43279787-52cd4e3e-910f-11e8-8761-497975ace89a.png)

**Comment by ClementNerma** [comment]
Bonjour,

L'erreur que vous obtenez ici est due au fait que le système ne trouve pas d'application pour gérer le bureau, or la gestion des applications n'existait pas encore au moment où le projet a été mis en pause. Il sera repris dans quelques temps mais nécessite beaucoup de travail de conception avant cela.
